### ISSUE TITLE
Netbox topic

### ISSUE THREAD

**Issue by xkilian** [candlerb/netbox-prometheus#2]
Add the Netbox topic to the repository so that it is listed in the Netbox list of plugins.

**Comment by candlerb** [comment]
Sorry, I don't understand that.  Can you expand?  I can't see anything called "topics" in the repository settings.

**Comment by xkilian** [comment]
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/classifying-your-repository-with-topics
Scroll down it show how to add a topic.
"netbox-plugin" That is the topic to use.

**Comment by candlerb** [comment]
Grr.  There is a settings wheel next to "About", which is different from the settings wheel next to "Settings".

Thanks for the pointer.
